version: '3.9'

services:
  chat-api:
    build:
      context: ./chat-api
      dockerfile: Dockerfile
    container_name: chat-api
    env_file:
      - ./chat-api/.env # <-- aquí pones LLM_API_KEY, LLM_MODEL, LLM_DOMAIN
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000' # opcional (útil para abrir Swagger directo)
    networks:
      - appnet

  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    depends_on:
      - chat-api
    ports:
      - '8080:80' # Frontend en http://localhost:8080
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
